# RScript TIN-Hydrotools Main
# Jan Schwanbeck and Martial Oggier, 2015/2016/2017

# Purpose: Determination of FlowPaths on Triangulated Irregular Network (TIN).
# Input:  Shapefile with nodes of TIN generated by external GIS-Software,
#         optional: nodes of river network
# Output: R-object with information on:
#                   - coordinates of nodes which define TIN-element 
#                   - coordinates of the centroid
#                   - gradient vector
#                   - coordinates of the point of intersection (POI)
#                   - attributes to define flow sections
#                   - aditional: parameters of the triangle
# Literature: Jones et al. 1990

# 0.) Load packages and functions
library(raster)
library(RTriangle)
setwd("C:/TEMP/moggier/Flow_Path_Project/TIN_tools")
source('tin_preprocessing_tools.R')
source('tin_hydrotools_flowpaths.R')
source('tin_hydrotools_drainage_system.R')

# 1.)  Read input 
# 1.1) DEM 
dem <- raster('C:/TEMP/moggier/bafu_turtmanntal/swissalti_2011_turt_10m.tif')
projection(dem)  <- CRS("+init=epsg:21781")

# 1.1) Data points of terrain surface (point shapefile)
fn <- 'Input/points_turt_z20.shp'
pts <- shapefile(fn)
plot(pts) 

# 1.2) Optional: Points of river network (point shapefile)
fn <- 'C:/TEMP/moggier/gwn/gwn25_turt_cleanII_pts.shp'
pts.gwn <- shapefile(fn)
dupl <- which(duplicated(pts.gwn@coords))
pts.gwn.uni <- pts.gwn[-dupl,]
plot(pts.gwn, col='blue')

pts.gwn.z <- extract(dem, pts.gwn.uni, sp=TRUE)
pts.gwn.z <- pts.gwn.z[-which(is.na(pts.gwn.z$swissalti_2011_turt_10m)),]

# 2.)  Prepare data storage object
# 2.1) Define the border of the TIN
pts.brd <- rbind(coordinates(pts)[8405,1:2],coordinates(pts)[9955,1:2],coordinates(pts)[30660,1:2],coordinates(pts)[25694,1:2])
points(x=pts.brd[,1], y=pts.brd[,2], col='yellow', pch=16, add=TRUE)

# 2.2) Triangulation
# PSLG without points of the river network
p <- RTriangle::pslg(P = coordinates(pts)[,1:2],PA = coordinates(pts)[,3],
                     S=rbind(c(8405, 9955), c(9955, 30660), c(30660, 25694), c(25694, 8405)))

# PSLG with points of the river network
pts.coords <- rbind(coordinates(pts)[,1:2],coordinates(pts.gwn.z)[,1:2])
pts.z  <- c(coordinates(pts)[,3],pts.gwn.z@data$swissalti_2011_turt_10m)
p <- RTriangle::pslg(P = pts.coords,PA = pts.z,
                     S=rbind(c(8405, 9955), c(9955, 30660), c(30660, 25694), c(25694, 8405)))

tp <- RTriangle::triangulate(p, D=TRUE)
plot(tp)
str(tp)

# 2.3) Assign heights to the added points
# Original points without points of the river network
pts.xy.ori <- paste(coordinates(pts)[,1],coordinates(pts)[,2],sep='_')

# Original points with points of the river network
pts.xy.ori <- paste(pts.coords[,1],pts.coords[,2],sep='_')

pts.xy.all <- paste(tp$P[,1],tp$P[,2],sep='_')

pts.new <- which(!(pts.xy.all%in%pts.xy.ori))
pts.new.z <- extract(dem, tp$P[pts.new,])
tp$PA[pts.new] <- pts.new.z

# 2.4) Create and populate data frame with input data
tpts <- cbind(tp$P,tp$PA); head(tpts)

dftin <- data.frame(TID=1:nrow(tp$T),
                    ax=tpts[tp$T[,1],1],
                    ay=tpts[tp$T[,1],2],
                    az=tpts[tp$T[,1],3],
                    bx=tpts[tp$T[,2],1],
                    by=tpts[tp$T[,2],2],
                    bz=tpts[tp$T[,2],3],
                    cx=tpts[tp$T[,3],1],
                    cy=tpts[tp$T[,3],2],
                    cz=tpts[tp$T[,3],3]); tail(dftin)

# 2.5) Preprocesssing of data
# Remove flat triangles
tpts1 <- mod_tri_flat(dftin, tpts)

# Remove pits
tpts1 <- rm_pits(dftin, tpts, pts.brd)

# Update data frame
dftin <- data.frame(TID=1:nrow(tp$T),
                    ax=tpts1[tp$T[,1],1],
                    ay=tpts1[tp$T[,1],2],
                    az=tpts1[tp$T[,1],3],
                    bx=tpts1[tp$T[,2],1],
                    by=tpts1[tp$T[,2],2],
                    bz=tpts1[tp$T[,2],3],
                    cx=tpts1[tp$T[,3],1],
                    cy=tpts1[tp$T[,3],2],
                    cz=tpts1[tp$T[,3],3]); tail(dftin)


# Remove faulty triangles 
tri.faulty <- find_tri_faulty(dftin)
dftin=dftin[-tri.faulty,]
rownames(dftin) <- NULL

# Create SpatialPolygons
tin.tri <- tri_polygons(dftin)
plot(tin.tri)

dftin.up=dftin

# 2.3) Sorting the nodes in clockwise direction
dftin <- sort_ccw(dftin)    


# 3.)  Calculate centroids
dftin <- centroid_triangle(dftin)


# 4.) Calculate maximum gradients and points of intersection
dftin <- steepest_descent_poi(dftin)   


# 5.) Find the relevant neighbour
dftin <- find_neigb(dftin)  


# 6.) Determine the flow type at the POI
dftin <- determine_flowtype(dftin)
  

# 7.) Determine the flow type at the vertex
dftin <- flowpath_vertex(dftin)

head(dftin)


# 9.) Define the flow segments
flowpaths <- flowsec_cen_poi(dftin) #1

flowpaths <- rbind(flowpaths,flowsec_poi_poi(dftin)) #2

flowpaths <- rbind(flowpaths,flowsec_ver_poi(dftin)) #4

channel <- flowsec_poi_ver(dftin) #3
channel <- rbind(channel,flowsec_ver_ver(dftin)) #5

flowsec.all <- missing_flowsections(dftin, flowpaths, channel)
flowpaths <- as.data.frame(flowsec.all[1]) #6
channel <- as.data.frame(flowsec.all[2]) #7

flowpaths <- rbind(flowpaths,arc_split(channel)); tail(flowpaths)

drain.sys <- flowpaths_lines(flowpaths)
plot(drain.sys, col='blue', add=TRUE)

# 10.) Delineate the watershed
ws <- watershed(end.arc, dftin)
dftin.ws <- dftin[ws,]


